### PR TITLE
Essential Rail scripts

### PR DESCRIPTION
**Pull request by hdante**
These are the essential rail scripts than can be used to trivially execute training and estimation with the pz-rail package. The pull request contains 3 scripts:

- rail-estimate: estimates the p(z) distributions given an input file
- rail-train: trains some algorithm for estimating
- install-pz-rail: install pz-rail and dependency libraries in a home directory using the conda package manager

The scripts have very slight configuration capabilities at the moment: they allow choosing between the flexzboost and bpz algorithms, the number of points in the resulting output functions and the names of the magnitude column names.

The scripts have the goal of filling the gap in the pz-rail package, which has no scripts for immediate execution at all, and could be pushed upstream if the pz-rail developers find it interesting to have them.

The pull request also includes documentation for getting started using the scripts.

### CODE REVIEW

**Comment by hdante** [comment]
I have pushed another commit with the requirements file.

**Comment by gschwend** [comment]
ciente, vou verificar 





	

Julia Gschwend 
Data Scientist 
[ https://www.linea.org.br/ | Site ] | [ https://twitter.com/LIneA_org | Twitter ] | [ https://www.instagram.com/linea_org/ | Instagram ] | [ https://www.facebook.com/linea.org | Facebook ] 
Laboratório Interinstitucional de e-Astronomia Nosso domínio mudou de .gov.br para .org.br 


De: "Henrique" ***@***.***> 
Para: "linea-it/pz-compute" ***@***.***> 
Cc: "julia" ***@***.***>, "Review requested" ***@***.***> 
Enviadas: Quinta-feira, 11 de maio de 2023 16:17:22 
Assunto: Re: [linea-it/pz-compute] Essential Rail scripts (PR #6) 





Hello, def_maglims disappeared from the latest version, so the BPZ algorithm is currently broken.

**Comment by hdante** [comment]
Hello, I've uploaded a second version of this patch set. Changes:
- Updated import of `def_maglims` to point to the new module location
- Cleanup the `load_slow_modules()` function.

**Review by crisingulani — APPROVED** [review]

**Comment by hdante** [comment]
Already merged together with #7

**Pull request closed without merging**
