### PR TITLE
Add missing requirements to the requirements file

### PR DESCRIPTION
**Pull request by hdante**

### CODE REVIEW

**Comment by hdante** [comment]
Rebased on top of current main branch without changes.

**Comment by crisingulani** [comment]
These packages are already in the install-pz-rail script

**Review by crisingulani — CHANGES_REQUESTED** [review]
@hdante These packages are already in the install-pz-rail script. Is it really necessary?

**Comment by hdante** [comment]
The `install-pz-rail` script is used to install upstream RAIL, independently of pz-compute, and contains its dependencies. The requirements file contains LineA pz-compute's dependencies. If they're to be used independently (running one but not the other, depending on the situation), then a some requirements will be duplicated.

**Review by crisingulani — APPROVED** [review]

**Review by HeloisaMengisztki — APPROVED** [review]

**Review by gschwend — APPROVED** [review]

**Pull request merged**
