### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by hdante**
A patchset with new documentation. Currently included:

- 7 manpages
- Script to generate the manpages from the asciidoc source

This patch depends on the lephare branch.

### CODE REVIEW

**Comment by hdante** [comment]
Uploaded another commit with the guide to adding new redshift estimators.

**Comment by hdante** [comment]
Sent version 2 of this patchset. Changes from version 1:

- This version was rebased on top of and now depends on the `misc-changes` branch.
- Changed all version identifiers to 0.2.0.
- Spelling/grammar fixes.
- Added a description of the `lepharedir` and `lepharework` parameters.
- Added the `pz-train` manpage.

**Comment by hdante** [comment]
Uploaded another commit with the `pz-train.yaml` manpage.

**Review by crisingulani — APPROVED** [review]

**Review by gschwend — APPROVED** [review]
I added a couple of commits to this branch, it will require a new round of review. Apart from in, the remaining files are approved. I tested all scripts following the instructions. Lephare is the only algorithm with remaining issues (to be solved in another dev branch). Also, to be added in a future branch, it is missing the documentation about the extinction correction in the preprocessing script. It is already implemented.

**Comment by gschwend** [comment]
@crisingulani veja meu último comentário. Dá uma olhadinha por favor nos meus últimos commits aqui nesse branch.

**Review by HeloisaMengisztki — APPROVED** [review]

**Pull request merged**
