### PR TITLE
Scheduler examples

### PR DESCRIPTION
**Pull request by hdante**
This patchset contains examples showing how to use the two schedulers used by LineA: HTCondor and slurm. The examples vary in complexity and some of them are the basis for more generally usable dispatch scripts, potentially for production.

The patch set contains the following examples:
- `rail-estimate-test`: trivial example that calls `rail-estimate` without any configuration parameters, assuming that input data will be located at input/test-<n>.hdf5 and the output at output/output-<n>.hdf5. It requests 10 jobs for 10 input files (fixed).
- `multi-rail-estimate`: An example that shows how to schedule estimation of multiple files per job with the goal of working around scheduler slowness or quota limits.
- `hello`: a trivial example for slurm, prints "Hello, World", can be used to show the speed of job dispatching with slurm.
- `multi-hello`: another example that shows how to execute multiple programs per slurm task, to work around batch quota limits.
- `rail-condor`: a more advanced HTCondor submission script, shows how to dispatch estimation of multiple files per task with non-uniform file names. This script can be used as is for production, or modified to increase parameter flexibility.

### CODE REVIEW

**Comment by hdante** [comment]
Updated patch set:
- fixups for `rail-condor`
- `rail-condor-preprocess`: efficiently preprocess input data to generate smaller files with proper data representation.
- `condor-dispatch`: HTCondor script to run arbitrary commands on the cluster.
- `condor-slot-run`: HTCondor script to run a command on a specific slot.
- `parquet-count-rows`: Script to count the total number of rows in parquet files.
- `test-cluster`: HTCondor script to show environment information about each slot in the cluster.

**Comment by crisingulani** [comment]
When testing this PR, I had a problem with the essential scripts `rail-train` and `rain-estimate` which are not on this branch. The solution was to copy them from the `rail-scripts-fixups` branch to a directory that is part of my $PATH. I think we need to add these scripts to this branch.

**Comment by crisingulani** [comment]
I'm having a problem running the `rail-train` for the fzboost algorithm (which doesn't happen for bpz), the catalog I'm using doesn't have mag_err, is that why?

```
(rail) singulani loginicx /lustre/t1/tmp/singulani/pz-compute >  (scheduler-examples) $ rail-train /lustre/t1/tmp/singulani/pz-compute/base_catalog.pq /lustre/t1/tmp/singulani/pz-compute/trained_flow.pkl --algorithm=fzboost --column-template=mag_{band}_lsst
Estimator algorithm: fzboost
Bins: 301
HDF5 group name: ""
Column template for magnitude data: "mag_{band}_lsst"
Column template for error data: "magerr_{band}"
Starting setup.
Loading all program modules...
Configuring trainer...
Loading input file...
Setup done.
Starting training.
stacking some data...
Traceback (most recent call last):
  File "/home/singulani/miniconda3/envs/rail/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3802, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5745, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5753, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'magerr_u'

```

**Comment by hdante** [comment]
Hello, the branches were developed independently. Do you want me to rebase this branch on top of the rail-scripts branch ?

**Comment by hdante** [comment]
Yes, `rail-train` requires the error columns because the train algorithms require them. Either check that the data file contains them and add `--column-template-error`, or a different train file will be needed.

**Comment by hdante** [comment]
Hello, BPZ should have worked with default parameters. Can you post the errors ? Which parameters will be necessary for it to work ?

The `rail-condor-preprocess` scripts depend on `rail-preprocess-parquet`. It's in a separate branch. I'll rebase it before this branch to make it easier to test it.

**Comment by hdante** [comment]
Hello, I've pushed version 3 with this patch set with the following change:

- Add 1 commit in the beginning with the `rail-preprocess-parquet` program

I'll also cancel the pull request for the separate rail-preprocess-parquet branch.

**Comment by hdante** [comment]
Hello, I've pushed version 4 with the following change:

- Add a comment in rail-condor-preprocess.sub explaining how to use it.

**Review by crisingulani — APPROVED** [review]

**Pull request merged**
